### ISSUE TITLE
MovieViewer

### ISSUE THREAD

**Issue by madhuryam** [madhuryam/MovieViewer#1]
@codepathreview

**Comment by vuminhkhang1995** [comment]
Hi,

I still cannot see any files except the MovieViewer.xcworkspace and your README. 

Could you please try to upload your work again with a filled-in README file for 2 weeks?

All the best,
Khang
_CodePath Grader_

**Comment by madhuryam** [comment]
What files should I upload? I wasn't sure if I needed anything else

**Comment by chieger** [comment]
You also need to have an animated gif showing a demo of your project. It should actually animate inside your README

Charlie

**Comment by madhuryam** [comment]
Okay, I think I fixed it. The 'v' at the end of the link was making it
unviewable.

**Comment by chieger** [comment]
Great, I can see your gif now! I don't see evidence of functioning tab bar in the gif and there are missing project files so I can't inspect your app delegate to see for myself.

Please either: 
- Update gif to show the tab bar in action
- Push ALL you project code so I can inspect the files

Thanks,
Charlie

**Comment by madhuryam** [comment]
I think I just uploaded all the project code.

**Comment by chieger** [comment]
I still do not see a README file and all the proper project related files.

You need to add...
- The README template for Part 1 Flicks with animated gif demo
- Add the README template for Part 2 Flicks to the bottom of the Part 1 README and add a gif of the part 2
- push the whole project

From the terminal can you do...
```
git add .
git commit -m "some comment"
gi push
```

Please let me know as soon as this is complete!

Thanks,
Charlie

**Comment by madhuryam** [comment]
I'm sorryy I'm new to this. But I just updated it!

On Feb 19, 2016, at 6:28 PM, Charlie Hieger <notifications@github.com>
wrote:

I still do not see a README file and all the proper project related files.

You need to add...

   - The README template for Part 1 Flicks with animated gif demo
   - Add the README template for Part 2 Flicks to the bottom of the Part 1
   README and add a gif of the part 2
   - push the whole project

From the terminal can you do...

git add .
git commit -m "some comment"
gi push

Please let me know as soon as this is complete!

Thanks,
Charlie

—
Reply to this email directly or view it on GitHub
<https://github.com/madhuryam/MovieViewer/issues/1#issuecomment-186449653>.
